### ISSUE TITLE
Only 30 repos are shown

### ISSUE THREAD

**Issue by stephenmcd** [KyroChi/GitHub-Profile-Fluency#1]
I looked at a profile with over 30 repos (my own) and only 30 repos are used. The language data is also looks skewed, presumably because not all repos are accounted for.

Glancing at the code, it looks like the cause is that you're not paginating the GitHub API results.

**Comment by stephenmcd** [comment]
BTW, it's a cool extension :-)

**Comment by KyroChi** [comment]
Glad you like it! I am looking into the pagination for the repository count, and with further research have found that the API serves up 30 repositories at a time, so I am working on a fix to display all of your repositories. This is also skewing the language data because it only pulls languages from the 30 repositories that it grabs from the API. 

Thank you for bringing this issue to my attention. I will try and get a fix out by the weekend :)

**Comment by KyroChi** [comment]
I fixed this problem, however I am not ready to re-upload the extension to the chrome store. (I ran into another problem while fixing this one :) (see issue #3 )) I will probably get v.1.5.0 up on the extension store tomorrow sometime.

 Thank you for bringing this problem to my attention. 

If you would like to use the updated version you can load the contents of the repository as an unpacked extension in chrome

-Kyle

P.S. Your profile graph is looking much more impressive now
![image](http://i.imgur.com/s9lnlJb.png)

I will try and tackle the accuracy this weekend too, so hopefully the statistics will better reflect the user's programming abilities, instead of just grabbing the top language from their created repositories
